In [32]:
import pandas as pd
import numpy as np
import os
annot_file='annotations_facs.csv'
meta_file='metadata_facs.csv'

In [51]:
annot=pd.read_csv(annot_file, dtype=str)
meta=pd.read_csv(meta_file)

In [52]:
annot.head()

,Neurog3>0_raw,Neurog3>0_scaled,cell,cell_ontology_class,cell_ontology_id,cluster.ids,free_annotation,mouse.id,mouse.sex,plate.barcode,...,subsetC,subsetC_cluster.ids,subsetD,subsetD_cluster.ids,subsetE,subsetE_cluster.ids,subtissue,tissue,tissue_tSNE_1,tissue_tSNE_2
0,NaN,NaN,A1.B000610.3_56_F.1.1,bladder cell,CL:1001319,5,Bladder mesenchymal cell,3_56_F,F,B000610,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bladder,-7.182841184579988,-10.895094373557567
1,NaN,NaN,A1.B002764.3_38_F.1.1,bladder urothelial cell,CL:1001428,3,Luminal bladder epithelial cell,3_38_F,F,B002764,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bladder,4.199059248070402,-11.050239873102482
2,NaN,NaN,A1.B002771.3_39_F.1.1,bladder cell,CL:1001319,5,Bladder mesenchymal cell,3_39_F,F,B002771,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bladder,-11.995435065265601,-7.325533500442496
3,NaN,NaN,A1.D041914.3_8_M.1.1,bladder cell,CL:1001319,5,Bladder mesenchymal cell,3_8_M,M,D041914,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bladder,-6.820021685160303,-14.174246453557148
4,NaN,NaN,A1.D042253.3_9_M.1.1,bladder cell,CL:1001319,2,Bladder mesenchymal cell,3_9_M,M,D042253,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bladder,-24.163537898804,-7.499349241905651

In [38]:
os.listdir('FACS')

['Fat-counts.csv',
 'Thymus-counts.csv',
 'Large_Intestine-counts.csv',
 'Heart-counts.csv',
 'Aorta-counts.csv',
 'Marrow-counts.csv',
 'Tongue-counts.csv',
 'Bladder-counts.csv',
 'Trachea-counts.csv',
 'Brain_Non-Myeloid-counts.csv',
 'Diaphragm-counts.csv',
 'Lung-counts.csv',
 'Mammary_Gland-counts.csv',
 'Liver-counts.csv',
 'Pancreas-counts.csv',
 'Skin-counts.csv',
 'Spleen-counts.csv',
 'Brain_Myeloid-counts.csv',
 'Kidney-counts.csv',
 'Limb_Muscle-counts.csv']

In [ ]:
temp = 0
for counts_file in os.listdir('FACS'):
    print('.')
    counts=pd.read_csv('FACS/'+counts_file)
    temp+=counts.shape[1]
print(temp)

In [46]:
counts_file = 'FACS/Fat-counts.csv'
counts=pd.read_csv(counts_file)
counts.iloc[0:5,:]

,Unnamed: 0,B15.MAA000385.3_10_M.1.1,D15.MAA000385.3_10_M.1.1,F15.MAA000385.3_10_M.1.1,L15.MAA000385.3_10_M.1.1,O4.MAA000385.3_10_M.1.1,P16.MAA000385.3_10_M.1.1,H18.MAA000385.3_10_M.1.1,J16.MAA000385.3_10_M.1.1,B17.MAA000385.3_10_M.1.1,...,N16.B002955.3_56_F.1.1,P9.B002955.3_56_F.1.1,P10.B002955.3_56_F.1.1,E16.B002955.3_56_F.1.1,H4.B002955.3_56_F.1.1,J4.B002955.3_56_F.1.1,L1.B002955.3_56_F.1.1,M9.B002955.3_56_F.1.1,N21.B002955.3_56_F.1.1,P11.B002955.3_56_F.1.1
0,0610005C13Rik,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0610007C21Rik,13,0,0,0,0,0,0,0,0,...,185,10,0,0,160,99,0,218,0,84
2,0610007L01Rik,70,0,0,0,4,0,0,0,1,...,58,0,0,0,0,0,0,0,0,188
3,0610007N19Rik,1,0,0,0,0,0,0,0,0,...,0,0,0,0,36,45,0,0,0,0
4,0610007P08Rik,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [61]:
cell_ids = counts.columns[1:]
QC_ids = list(annot['cell'])
QC_annot = list(annot['free_annotation'].astype(str))

In [73]:
temp = [x for x in cell_ids if x in QC_ids]
counts = counts.loc[:,['Unnamed: 0']+temp]

,Unnamed: 0,B15.MAA000385.3_10_M.1.1,D15.MAA000385.3_10_M.1.1,F15.MAA000385.3_10_M.1.1,L15.MAA000385.3_10_M.1.1,O4.MAA000385.3_10_M.1.1,P16.MAA000385.3_10_M.1.1,H18.MAA000385.3_10_M.1.1,J16.MAA000385.3_10_M.1.1,B17.MAA000385.3_10_M.1.1,...,K15.B002955.3_56_F.1.1,M7.B002955.3_56_F.1.1,N16.B002955.3_56_F.1.1,P9.B002955.3_56_F.1.1,P10.B002955.3_56_F.1.1,E16.B002955.3_56_F.1.1,H4.B002955.3_56_F.1.1,J4.B002955.3_56_F.1.1,M9.B002955.3_56_F.1.1,P11.B002955.3_56_F.1.1
0,0610005C13Rik,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0610007C21Rik,13,0,0,0,0,0,0,0,0,...,0,441,185,10,0,0,160,99,218,84
2,0610007L01Rik,70,0,0,0,4,0,0,0,1,...,0,219,58,0,0,0,0,0,0,188
3,0610007N19Rik,1,0,0,0,0,0,0,0,0,...,0,13,0,0,0,0,36,45,0,0
4,0610007P08Rik,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23428,Zzef1,0,3,0,0,0,0,0,0,7,...,304,0,0,4,0,0,0,60,0,22
23429,Zzz3,29,0,0,0,0,30,50,0,12,...,0,237,0,0,0,0,0,131,1,0
23430,a,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23431,l7Rn6,64,0,1,0,0,0,113,0,3,...,0,90,0,0,0,0,30,88,0,0
23432,zsGreen_transgene,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0